# Generated by Django 4.0.3 on 2022-03-28 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Featuredproduct',
        ),
    ]
