# Generated by Django 4.0.3 on 2022-03-29 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_product_featuredproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address',
            field=models.CharField(default='hometown_admin', max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='mpesacode',
            field=models.CharField(default='admin', max_length=10),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='phone',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='state',
            field=models.CharField(default='admin', max_length=200),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='zipcode',
            field=models.CharField(default='admin', max_length=200),
        ),
    ]
